#!/bin/sh
# Description: Script to get battery status

for battery in /sys/class/power_supply/BAT?; do
    percent=$(cat "$battery/capacity")  # battery percentage
    status="$(cat "$battery/status")"   # battery status

    [ "$status" = "Charging" ] && BATTERY_ICON="" || BATTERY_ICON=""

    if [ "$percent" -gt 70 ]; then      # status2d
        printf "^c#B9CC81^"
    elif [ "$percent" -gt 30 ]; then
        printf "^c#F5BF03^"
    else
        printf "^c#DB695B^"
    fi
    printf "%s %d%%^d^" "$BATTERY_ICON" "$percent"
done && exit 0
